
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  # Minimal configuration of the standard time and date sensor
  - platform: time_date
    display_options:
      - 'date'
      - 'time'

frontend:
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js



lovelace:
  mode: yaml
  resources:
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/kiosk-mode/kiosk-mode.js
      type: module
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/community/sidebar-card/sidebar-card.js
      type: module
  dashboards:
    lovelace-ui:
      mode: yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ui-lovelace.yaml