kiosk_mode:
  user_settings:
    - users:
        - tablet
      hide_sidebar: true
      hide_header: true
      hide_menu_button: true
      hide_overflow: true
      kiosk: true

button_card_templates: !include button_card_templates.yaml

sidebar:
  style: |
    :host {
        --sidebar-background: #1a1b1e;
        --sidebar-text-color: #FFF;
        --face-color: #a9a9a7;
        --face-border-color: #000;
      }
  digitalClock: true
  date: true
  dateFormat: dddd, DD MMMM YYYY
  width:
    mobile: 0
    tablet: 30
    desktop: 25
  sidebarMenu:
    - action: navigate
      navigation_path: "/lovelace/home"
      name: "Home"
      active: true
    - action: navigate
      navigation_path: "/lovelace/lampen"
      name: "Letto Singolo"
    - action: navigate
      navigation_path: "/lovelace/music"
      name: "Letto Doppio"
    - action: navigate
      navigation_path: "/lovelace/4"
      name: "Bagno"

views:
  - title: HOME
    path: home
    panel: true
    background: >-
      center / cover no-repeat fixed
      url('/local/images/background1.jpg')
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: 'custom:mod-card'
                style:
                   hui-vertical-stack-card$: |
                    #root {
                      margin: 10px !important;
                    }
                card:
                  type: vertical-stack
                  cards:
                    - !include demo/home/body_row_1.yaml
                    - !include demo/home/body_row_2.yaml