kiosk_mode:
  user_settings:
    - users:
        - tablet
      hide_sidebar: true
      hide_header: true
      hide_menu_button: true
      hide_overflow: true
      kiosk: true
      
button_card_templates: !include button_card_templates.yaml
views:
  - title: HOME
    path: home
    panel: true
    background: >-
      center / cover no-repeat fixed
      url('/local/images/background.jpg')
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 30% 70%
          grid-template-rows: 100%
          grid-template-areas: |
            "sidebar body"
          height: 100%
          margin: 0px
          mediaquery:
            "(max-width: 600px)":
            grid-template-columns: 100%
            grid-template-areas: |
              "sidebar"
              "body"
            "(max-width: 800px)":
              grid-template-columns: 20% 70%
              grid-template-areas: |
                "sidebar body"
        cards:
          - type: custom:mod-card
            style: |
                ha-card {
                    background: rgba(0,0,0,0.3);
                    height: 100%;
                }
            view_layout:
              grid-area: sidebar
            card:
              !include demo/home/sidebar.yaml
          - type: vertical-stack
            view_layout:
              grid-area: body
            cards:
              - !include demo/home/header.yaml
              - type: 'custom:mod-card'
                style:
                   hui-vertical-stack-card$: |
                    #root {
                      margin: 10px !important;
                    }
                card:
                  type: vertical-stack
                  cards:
                    - !include demo/home/body_nav.yaml
                    - !include demo/home/body_row_1.yaml
                    - !include demo/home/body_row_2.yaml
